#!/bin/sh

docker=podman

run_keycloak() {

    "$docker" run --rm --name poc_keycloak \
        -e KEYCLOAK_ADMIN=admin \
        -e KEYCLOAK_ADMIN_PASSWORD=admin \
        --network=host \
        -v "$(pwd)/import:/opt/keycloak/data/import" \
        quay.io/keycloak/keycloak:25.0 \
        start-dev \
        --http-port=8180 --import-realm

}

run_client() {
    FLASK_APP=client.py flask run "$@"
}

run_rs() {
    FLASK_APP=rs.py flask run "$@"
}

case "$1" in
    run)
        case "$2" in
            keycloak)
                run_keycloak
            ;;
            client1)
                INDEX=1 run_client -p8091
            ;;
            client2)
                INDEX=2 run_client -p8092
            ;;
            rs1)
                INDEX=1 run_rs -p8081
            ;;
            rs2)
                INDEX=2 run_rs -p8082
            ;;
            *)
                printf "Bad command\n" 2>&1 
                exit 1
            ;;
        esac
    ;;
    browse)
        case "$2" in
            client1)
                xdg-open http://localhost:8091/
            ;;
            client2)
                xdg-open http://localhost:8092/
            ;;
            *)
                printf "Bad command\n" 2>&1 
                exit 1
            ;;
        esac
    ;;
    *)
        printf "Bad command\n" 2>&1 
        exit 1
    ;;
esac
